name: DEV - Build, Push & Deploy

on:
  push:
    branches:
      - dev

jobs:
  worker-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIP }}
        service_account: ${{ secrets.DEV_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        access_token_lifetime: '300s'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.DEV_GCP_PROJECT }}

    - name: Build Docker image
      working-directory: ./worker
      run: docker build -t europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/worker:latest -t europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/worker:${{ github.sha }} .

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev --quiet --project ${{ secrets.DEV_GCP_PROJECT }}

    - name: Push Docker SHA tagged image to Artifact Registry
      run: docker push europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/worker:${{ github.sha }}

    - name: Push Docker latest tagged image to Artifact Registry
      run: docker push europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/worker:latest

  api-build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIP }}
        service_account: ${{ secrets.DEV_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        access_token_lifetime: '300s'

    # Install UI Dependencies
    - name: Install UI Dependencies
      working-directory: ./api/ui
      run: npm install

    # Build Litmus UI
    - name: Build Litmus UI
      working-directory: ./api/ui
      run: npm run build

    - name: Build Docker image
      working-directory: ./api
      run: docker build -t europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/api:latest -t europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/api:${{ github.sha }} .

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev --quiet --project ${{ secrets.DEV_GCP_PROJECT }}

    - name: Push Docker SHA tagged image to Artifact Registry
      run: docker push europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/api:${{ github.sha }}

    - name: Push Docker latest tagged image to Artifact Registry
      run: docker push europe-docker.pkg.dev/${{ secrets.DEV_GCP_PROJECT }}/litmus/api:latest

  cli-build-store:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIP }}
        service_account: ${{ secrets.DEV_SERVICE_ACCOUNT }}
        token_format: 'access_token'
        access_token_lifetime: '300s'

    # Install GO
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23' 

    # Build & Store
    - name: Build & Store
      working-directory: ./cli
      run: |
        go install
        go build main.go
        sha256sum main > litmus.sha256
        gcloud storage cp main gs://litmus-cloud/dev/linux/litmus
        gcloud storage cp litmus.sha256 gs://litmus-cloud/dev/linux/litmus.sha256
        env GOOS=darwin GOARCH=amd64 go build main.go
        sha256sum main > litmus.sha256
        gcloud storage cp main gs://litmus-cloud/dev/osx/litmus
        gcloud storage cp litmus.sha256 gs://litmus-cloud/dev/osx/litmus.sha256

    # Deploy
    - name: Deploy
      working-directory: ./
      run: |
        go install
        wget https://storage.googleapis.com/litmus-cloud/dev/linux/litmus
        chmod 755 ./litmus
        ./litmus deploy --project litmusai-dev --quiet